2019-03-22 08:28:26.082  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 34603612ms for sessionid 0x100fc439b1b01b4
2019-03-22 08:28:26.538  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 34603612ms for sessionid 0x100fc439b1b01b4, closing socket connection and attempting reconnect
2019-03-22 08:28:26.654  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Disconnected)
2019-03-22 08:28:27.922  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:27.925 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:27.956  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:29.767  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:29.768 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:29.769  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:31.407  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:31.408 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:31.408  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:33.259  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:33.261 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:33.264  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:35.141  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:35.144 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:35.146  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:37.101  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:37.104 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:37.107  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:38.878  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:38.880 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:38.882  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:28:40.094  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:28:40.097 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:28:40.098  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:18.132  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:18.133 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:18.280  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:20.296  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:20.297 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:20.299  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:22.018  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:22.019 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:22.021  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:23.543  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:23.544 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:23.544  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:25.369  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:25.375 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:25.376  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:27.251  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:27.251 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:27.252  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:29.258  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:29.261 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:29.263  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:31.134  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:31.136 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:31.144  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:32.906  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:32.909 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:44:32.911  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b4 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:44:34.383  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:34.389  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-22 08:44:34.394  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b01b4 has expired
2019-03-22 08:44:34.394  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Expired)
2019-03-22 08:44:34.394  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b01b4 has expired, closing socket connection
2019-03-22 08:44:34.394  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.170.0.42:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@3db414ee
2019-03-22 08:44:34.395  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:44:34.396  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b01b4
2019-03-22 08:44:34.398  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-22 08:44:34.405  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b01b5, negotiated timeout = 30000
2019-03-22 08:44:34.405  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
2019-03-22 08:45:27.292  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 52880ms for sessionid 0x100fc439b1b01b5
2019-03-22 08:45:27.292  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 52880ms for sessionid 0x100fc439b1b01b5, closing socket connection and attempting reconnect
2019-03-22 08:45:27.402  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Disconnected)
2019-03-22 08:45:27.402  INFO 43521 --- [ZkClient-EventThread-39-192.170.0.42:2181] org.I0Itec.zkclient.ZkClient             : Waiting for keeper state SyncConnected
2019-03-22 08:45:28.978  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:45:28.979 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:45:28.979  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b5 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:45:29.084  INFO 43521 --- [DubboRegistryFailedRetryTimer-thread-1] org.I0Itec.zkclient.ZkClient             : Waiting for keeper state SyncConnected
2019-03-22 08:45:30.938  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:45:30.938 ERROR 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] o.apache.zookeeper.ClientCnxnSocketNIO   : Unable to open socket to 192.170.0.42/192.170.0.42:2181
2019-03-22 08:45:30.938  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x100fc439b1b01b5 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.SocketException: Network is unreachable
	at sun.nio.ch.Net.connect0(Native Method) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:454) ~[na:1.8.0_171]
	at sun.nio.ch.Net.connect(Net.java:446) ~[na:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[na:1.8.0_171]
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1024) ~[zookeeper-3.4.8.jar:3.4.8--1]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060) ~[zookeeper-3.4.8.jar:3.4.8--1]

2019-03-22 08:45:32.560  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:45:32.563  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-22 08:45:32.567  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Expired)
2019-03-22 08:45:32.567  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=192.170.0.42:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@3db414ee
2019-03-22 08:45:32.567  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b01b5 has expired
2019-03-22 08:45:32.567  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Unable to reconnect to ZooKeeper service, session 0x100fc439b1b01b5 has expired, closing socket connection
2019-03-22 08:45:32.569  INFO 43521 --- [DubboZkclientConnector-EventThread] org.apache.zookeeper.ClientCnxn          : EventThread shut down for session: 0x100fc439b1b01b5
2019-03-22 08:45:32.570  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:45:32.573  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-22 08:45:32.579  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b01b7, negotiated timeout = 30000
2019-03-22 08:45:32.579  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
2019-03-22 08:46:20.938  WARN 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 20002ms for sessionid 0x100fc439b1b01b7
2019-03-22 08:46:20.939  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Client session timed out, have not heard from server in 20002ms for sessionid 0x100fc439b1b01b7, closing socket connection and attempting reconnect
2019-03-22 08:46:21.040  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (Disconnected)
2019-03-22 08:46:22.197  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 192.170.0.42/192.170.0.42:2181. Will not attempt to authenticate using SASL (unknown error)
2019-03-22 08:46:39.626  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 192.170.0.42/192.170.0.42:2181, initiating session
2019-03-22 08:46:39.629  INFO 43521 --- [DubboZkclientConnector-SendThread(192.170.0.42:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 192.170.0.42/192.170.0.42:2181, sessionid = 0x100fc439b1b01b7, negotiated timeout = 30000
2019-03-22 08:46:39.630  INFO 43521 --- [DubboZkclientConnector-EventThread] org.I0Itec.zkclient.ZkClient             : zookeeper state changed (SyncConnected)
